# Assignment 17: Text Cleaning, Preprocessing and NLP Pipeline

In [408]:
import pandas as pd
import numpy as np

Dataset Name: TMDB 5000 Movie Dataset

Kaggle Link: https://www.kaggle.com/datasets/tmdb/tmdb-movie-metadata

## Part 1 : NLP Pipeline & Basic Text Cleaning

### Task 1: Understanding Raw Text Data

In [409]:
df = pd.read_csv('./IMDB Dataset.csv')

In [410]:
data = df.copy()

In [411]:
data.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [412]:
data.shape

(50000, 2)

In [413]:
data.sample(5)

                                                  review sentiment
1408   I saw this film as a kid about 30 years ago, a...  positive
4413   The movie Jennifer with Ida Lupino and Howard ...  positive
49156  Having watched this movie on the SciFi channel...  negative
1309   Halloween 666 (1995) The producer's cut review...  positive
2078   I loved October Sky. The thing I loved most ha...  positive

In [414]:
data['review'].head()

0    One of the other reviewers has mentioned that ...
1    A wonderful little production. <br /><br />The...
2    I thought this was a wonderful way to spend ti...
3    Basically there's a family where a little boy ...
4    Petter Mattei's "Love in the Time of Money" is...
Name: review, dtype: str

Text Length

In [415]:
data['text_length'] = data['review'].str.len()

In [416]:
data[['review', 'text_length']].head()

                                              review  text_length
0  One of the other reviewers has mentioned that ...         1761
1  A wonderful little production. <br /><br />The...          998
2  I thought this was a wonderful way to spend ti...          926
3  Basically there's a family where a little boy ...          748
4  Petter Mattei's "Love in the Time of Money" is...         1317

In [417]:
data['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

Uppercase

In [418]:
any(char.isupper() for char in data['review'][0])

True

In [419]:
import re

In [420]:
numbers = re.findall(r'\d+', data['review'][0])
numbers

['1']

Extra Space

In [421]:
"  " in data['review'][0]

False

In [422]:
"  " in data['review'][1]

False

Html Tage

In [423]:
html = re.findall(r"<.*?>", data['review'][0])
html

['<br />', '<br />', '<br />', '<br />', '<br />', '<br />']

Punctuation

In [424]:
punctuation = re.findall(r"[^\w\s]", data['review'][1])
punctuation[:30]

['.',
 '<',
 '/',
 '>',
 '<',
 '/',
 '>',
 '-',
 '-',
 '-',
 ',',
 ',',
 '.',
 '<',
 '/',
 '>',
 '<',
 '/',
 '>',
 '-',
 '"',
 '"',
 '!',
 "'",
 ',',
 '.',
 "'",
 '.',
 '<',
 '/']

### Task 2: Basic Text Cleaning

In [425]:
def apply_lower_case(text):
    return text.lower()

In [426]:
data['review'] = data['review'].apply(apply_lower_case)

In [427]:
def punctuation_removal(text):
    return re.sub(r'[^\w\s]', '', text)

In [428]:
data['review'] = data['review'].apply(punctuation_removal)

In [429]:
punctuation = re.findall(r"[^\w\s]", data['review'][1])
punctuation[:30]

[]

In [430]:
def remove_html_tage(text):
    return re.sub(r"<.*?>", '', text)

In [431]:
data['review'] = data['review'].apply(remove_html_tage)

In [432]:
html = re.findall(r"<.*?>", data['review'][0])
html

[]

In [433]:
def remove_numbers(text):
    return re.sub(r"\d+", "", text)

In [434]:
data['review'] = data['review'].apply(remove_numbers)

In [435]:
def remove_extra_space(text):
    return re.sub(r"\s+", " ", text).strip()

In [436]:
data['review'] = data['review'].apply(remove_extra_space)

In [437]:
data['clean_text_basic'] = data['review']

In [438]:
comparison = pd.DataFrame({'df1_review': df['review'], 'df2_review': data['review']})

In [439]:
comparison = comparison[comparison['df1_review'] != comparison['df2_review']]

In [440]:
comparison

,df1_review,df2_review
0,One of the other reviewers has mentioned that ...,one of the other reviewers has mentioned that ...
1,A wonderful little production. <br /><br />The...,a wonderful little production br br the filmin...
2,I thought this was a wonderful way to spend ti...,i thought this was a wonderful way to spend ti...
3,Basically there's a family where a little boy ...,basically theres a family where a little boy j...
4,"Petter Mattei's ""Love in the Time of Money"" is...",petter matteis love in the time of money is a ...
...,...,...
49995,I thought this movie did a down right good job...,i thought this movie did a down right good job...
49996,"Bad plot, bad dialogue, bad acting, idiotic di...",bad plot bad dialogue bad acting idiotic direc...
49997,I am a Catholic taught in parochial elementary...,i am a catholic taught in parochial elementary...
49998,I'm going to have to disagree with the previou...,im going to have to disagree with the previous...
49999,No one expects the Star Trek movies to be high...,no one expects the star trek movies to be high...

## Part 2: Advanced Text Cleaning

### Task 3: Removing Noise

In [441]:
def url_removal(text):
    return re.sub(r"https?://\S+|www\.\S+", '', text)

In [442]:
data['review'] = data['review'].apply(url_removal)

In [443]:
def email_removal(text):
    return re.sub(r"https?://\S+|www\.\S+", '', text)

In [444]:
data['review'] = data['review'].apply(email_removal)

In [445]:
def remove_html_tags(text):
    return re.sub(r'<.*?>', '', text)

In [446]:
data['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production br br the filmin...
2        i thought this was a wonderful way to spend ti...
3        basically theres a family where a little boy j...
4        petter matteis love in the time of money is a ...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot bad dialogue bad acting idiotic direc...
49997    i am a catholic taught in parochial elementary...
49998    im going to have to disagree with the previous...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: str

In [447]:
data['review'] = data['review'].apply(remove_html_tags)

In [448]:
def remove_emoji(text):
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"  # Emoticons
        "\U0001F300-\U0001F5FF"  # Symbols & Pictographs
        "\U0001F680-\U0001F6FF"  # Transport
        "\U0001F1E0-\U0001F1FF"  # Flags
        "\U00002700-\U000027BF"
        "\U000024C2-\U0001F251"
        "]+",
        flags=re.UNICODE
    )

    return emoji_pattern.sub('', text)

In [449]:
data['review'] =data['review'].apply(remove_emoji)

In [450]:
def remove_special_character(text):
    return re.sub(r'[^a-zA-Z\s]', '', text)

In [451]:
data['review'] =data['review'].apply(remove_special_character)

In [452]:
data['clean_text_advanced'] = data['review']

In [453]:
data['clean_text_advanced']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production br br the filmin...
2        i thought this was a wonderful way to spend ti...
3        basically theres a family where a little boy j...
4        petter matteis love in the time of money is a ...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot bad dialogue bad acting idiotic direc...
49997    i am a catholic taught in parochial elementary...
49998    im going to have to disagree with the previous...
49999    no one expects the star trek movies to be high...
Name: clean_text_advanced, Length: 50000, dtype: str

In [454]:
data['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production br br the filmin...
2        i thought this was a wonderful way to spend ti...
3        basically theres a family where a little boy j...
4        petter matteis love in the time of money is a ...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot bad dialogue bad acting idiotic direc...
49997    i am a catholic taught in parochial elementary...
49998    im going to have to disagree with the previous...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: str

## Task 4: Handling Stopwords

In [455]:
import nltk

In [456]:
from nltk.corpus import stopwords

In [457]:
english = stopwords.words("english")

In [458]:
def stopwords_removal(text):
    li = []
    for i in text.split():
        if i in english:
            li.append('')
        else:
            li.append(i)
    
    x = li[:]
    li.clear()
    return " ".join(x)

In [459]:
data['text_no_stopwords'] =data['clean_text_advanced'].apply(stopwords_removal)

In [460]:
data['text_no_stopwords']

0        one    reviewers  mentioned   watching  oz epi...
1         wonderful little production br br  filming te...
2         thought    wonderful way  spend time    hot s...
3        basically theres  family   little boy jake thi...
4        petter matteis love   time  money   visually s...
                               ...
49995     thought  movie    right good job  wasnt  crea...
49996    bad plot bad dialogue bad acting idiotic direc...
49997       catholic taught  parochial elementary schoo...
49998    im going    disagree   previous comment  side ...
49999     one expects  star trek movies   high art   fa...
Name: text_no_stopwords, Length: 50000, dtype: str

## Task 5: Hanlding Repeated Characters & Slang(Optional)

In [461]:
def remove_repeated_characters(text):
    return re.sub(r'(.)\1{2,}', r'\1', text)

In [462]:
slang_dict = {
    "u": "you",
    "ur": "your",
    "gr8": "great",
    "btw": "by the way",
    "idk": "i do not know",
    "lol": "laughing",
    "omg": "oh my god",
    "thx": "thanks",
    "pls": "please",
    "msg": "message",
    "b4": "before",
    "luv": "love"
}

In [463]:
def replace_slang(text):
    words = text.split()

    new_words = [
        slang_dict[word] if word in slang_dict else word
        for word in words
    ]

    return " ".join(new_words)

In [464]:
data['text_no_stopwords']

0        one    reviewers  mentioned   watching  oz epi...
1         wonderful little production br br  filming te...
2         thought    wonderful way  spend time    hot s...
3        basically theres  family   little boy jake thi...
4        petter matteis love   time  money   visually s...
                               ...
49995     thought  movie    right good job  wasnt  crea...
49996    bad plot bad dialogue bad acting idiotic direc...
49997       catholic taught  parochial elementary schoo...
49998    im going    disagree   previous comment  side ...
49999     one expects  star trek movies   high art   fa...
Name: text_no_stopwords, Length: 50000, dtype: str

In [465]:
data["text_no_stopwords"] =data["text_no_stopwords"].apply(remove_repeated_characters)

In [466]:
data["text_no_stopwords"] = data["text_no_stopwords"].apply(replace_slang)

## Task 6: Tokenization

In [467]:
from nltk.tokenize import word_tokenize, sent_tokenize

In [468]:
data["word_tokens"] = data["clean_text_advanced"].apply(word_tokenize)

In [469]:
data['word_tokens']

0        [one, of, the, other, reviewers, has, mentione...
1        [a, wonderful, little, production, br, br, the...
2        [i, thought, this, was, a, wonderful, way, to,...
3        [basically, theres, a, family, where, a, littl...
4        [petter, matteis, love, in, the, time, of, mon...
                               ...
49995    [i, thought, this, movie, did, a, down, right,...
49996    [bad, plot, bad, dialogue, bad, acting, idioti...
49997    [i, am, a, catholic, taught, in, parochial, el...
49998    [im, going, to, have, to, disagree, with, the,...
49999    [no, one, expects, the, star, trek, movies, to...
Name: word_tokens, Length: 50000, dtype: object

In [470]:
data["sentence_tokens"] = data["review"].apply(sent_tokenize)

In [471]:
data['sentence_tokens'].head()

0    [one of the other reviewers has mentioned that...
1    [a wonderful little production br br the filmi...
2    [i thought this was a wonderful way to spend t...
3    [basically theres a family where a little boy ...
4    [petter matteis love in the time of money is a...
Name: sentence_tokens, dtype: object

In [472]:
data['word_tokens'].sample(3)

25987    [one, of, the, better, made, for, tv, biopics,...
34090    [the, film, transported, everyone, back, to, o...
23853    [if, you, thought, rosemarys, baby, was, bad, ...
Name: word_tokens, dtype: object

## Task 7: Stemming

In [473]:
from nltk.stem import PorterStemmer

ps = PorterStemmer()

In [474]:
def stemming_words(words):
    return [ps.stem(word) for word in words]

In [475]:
data['stemmed_words'] = data['word_tokens'].apply(stemming_words)

## Task 8 : Lemmatization

In [476]:
from nltk.stem import WordNetLemmatizer

In [477]:
lemmatizer = WordNetLemmatizer()

In [478]:
# def lemmatize_words(tokens):
#     return [lemmatizer.lemmatize(word) for word in tokens]

In [479]:
def lemmatize_words(tokens):
    clean_words = []
    for word in tokens:
        root_word = lemmatizer.lemmatize(word)
        clean_words.append(root_word)
    return clean_words

In [480]:
data["lemmatized_words"] = data["word_tokens"].apply(lemmatize_words)

# Task 9: Final NLP Pipeline Creation

In [481]:
import string
from nltk import pos_tag
from nltk.corpus import wordnet

In [486]:
nltk.download("averaged_perceptron_tagger_eng")

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\arunk\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger_eng.zip.

True

In [482]:
stop_words = set(stopwords.words("english"))

In [483]:
def get_wordnet_pos(tag):

    if tag.startswith("J"):
        return wordnet.ADJ

    elif tag.startswith("V"):
        return wordnet.VERB

    elif tag.startswith("N"):
        return wordnet.NOUN

    elif tag.startswith("R"):
        return wordnet.ADV

    return wordnet.NOUN

In [484]:
def nlp_preprocess(text):
    text = text.lower()
    text = re.sub(r'https?://\S+|www\.\S+','',text)

    text = re.sub(r'\S+@\S+','',text)

    text = re.sub(r'<.*?>','',text)
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = re.sub(r'\d+','',text)
    text = re.sub(r'[^a-zA-Z\s]','',text)

    text = re.sub(r'\s+',' ',text).strip()

    tokens = word_tokenize(text)
    tokens = [
        word
        for word in tokens
        if word not in stop_words
    ]

    pos_tags = pos_tag(tokens)

    lemmatized_words = []

    for word, tag in pos_tags:
        wordnet_pos = get_wordnet_pos(tag)
        lemma = lemmatizer.lemmatize(
            word,
            pos=wordnet_pos
        )

        lemmatized_words.append(lemma)
    return " ".join(lemmatized_words)

In [487]:
data['final_clean_text'] = df['review'].apply(nlp_preprocess)

In [488]:
data[["review","final_clean_text"]].head()

,review,final_clean_text
0,one of the other reviewers has mentioned that ...,one reviewer mention watch oz episode youll ho...
1,a wonderful little production br br the filmin...,wonderful little production film technique una...
2,i thought this was a wonderful way to spend ti...,think wonderful way spend time hot summer week...
3,basically theres a family where a little boy j...,basically there family little boy jake think t...
4,petter matteis love in the time of money is a ...,petter matteis love time money visually stunni...

## Task 10: Observations and Insights

1. Difference Between Basic and Advanced Cleaning

Basic Cleaning: removing Lowecasing, removing punctuation, numbers and extra spaces. Purpose is make raw text consistent and easier to process

Advanced Cleaning: Removing noise, such as URLS, email address, html tags, emoji and special character. handle issues such as repeated character and slang also

2. Why Lemmatization Is Preferred Over Stemming
I prefer lemmatization because it make language correctiona and meaning are important because Stemming simply cuts prefix or suffixes and can produce words that are not valid 

- Stemming
eg. movies --> movi 

- Lemmatization
eg. movies --> movie 

Lemmatization produce more meaningful results


3. Importance of Preprocessing in NLP Models
- It is important bceuase raw text is incosistnet, noisy and unstructured
- Preprocessing helps removing noise, reduce vocabulary size, convert word into meaning representation, improve quality of feature 
- reduce unneccessary computational work