# `Real World Datasets in Series`
---

In [13]:
import pandas as pd

## `read_csv()`
- this function reads the content from the csv file in pandas
- We can perform operations or effective analysis on the data

In [14]:
df = pd.read_csv('../Datasets/youtube_2025_dataset_202504061614.csv')

In [15]:
df

,Channel Name,Youtuber Name,Total Videos,Best Video,Avg Video Length (min),Total Subscribers,Members Count,AI Generated Content (%),Neural Interface Compatible,Metaverse Integration Level,Quantum Computing Topics,Holographic Content Rating,Engagement Score,Content Value Index
0,Smith-Ross Labs,Eric Patel,68,VR Challenge: Review 2023,24.8,8264152,303319,9,True,Full,5,3D,130655.44,6.2
1,Sandoval PLC Hub,Cynthia Harrington,128,Nanotech Simulation: Analysis 2024,22.9,8768222,384629,62,False,NaN,4,3D,138624.73,21.4
2,"Jones, Moore and Ho Network",Amanda Walker,282,Metaverse Interface: Analysis 2024,24.0,6163386,361743,31,True,Advanced,6,1D,97442.53,13.5
3,Mitchell-Hooper Labs,Jessica Nelson MD,302,VR Protocol: Review 2023,24.6,4712268,58483,5,False,NaN,15,1D,74500.50,12.0
4,Wilson LLC Studios,Matthew Sherman,129,Nanotech Simulation: Review 2024,24.6,9592017,333873,63,True,NaN,12,3D,151648.85,27.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Flores-Daniel Studios,Jasmine Smith,106,AI Challenge: Experience 2023,22.0,2665835,267828,19,True,Full,1,3D,42146.59,6.4
4996,Spencer and Sons Studios,John Rasmussen,130,VR Challenge: Analysis 2023,26.3,136992,20019,67,True,Full,14,4D,2165.83,29.9
4997,Obrien-Roberts Studios,Lisa Burke,179,AI Challenge: Experience 2023,25.2,2314561,407346,99,True,Advanced,5,1D,36592.98,33.2
4998,King Ltd Hub,Steve Diaz,182,VR Synthesis: Showcase 2023,24.5,6954832,308313,1,True,Basic,9,4D,109955.22,6.6
4999,Henry Ltd Studios,Austin Tate,92,AI Simulation: Showcase 2025,25.2,6785166,23263,52,True,Full,8,3D,107272.81,21.2

## `Dataframe`:
- combination of Multiple Series( Columns )

### `squeeze` : make sure that the data should be in series format

In [16]:
# without squeeze, type is dataframe
df_one = pd.read_csv("../Datasets/youtube_2025_dataset_one_column.csv")
print(df)
print("\n")
print(type(df_one))

                     Channel Name       Youtuber Name  Total Videos  \
0                 Smith-Ross Labs          Eric Patel            68
1                Sandoval PLC Hub  Cynthia Harrington           128
2     Jones, Moore and Ho Network       Amanda Walker           282
3            Mitchell-Hooper Labs   Jessica Nelson MD           302
4              Wilson LLC Studios     Matthew Sherman           129
...                           ...                 ...           ...
4995        Flores-Daniel Studios       Jasmine Smith           106
4996     Spencer and Sons Studios      John Rasmussen           130
4997       Obrien-Roberts Studios          Lisa Burke           179
4998                 King Ltd Hub          Steve Diaz           182
4999            Henry Ltd Studios         Austin Tate            92

                              Best Video  Avg Video Length (min)  \
0              VR Challenge: Review 2023                    24.8
1     Nanotech Simulation: Analysis 2024                    22.9
2     Metaverse Interface: Analysis 2024                    24.0
3               VR Protocol: Review 2023                    24.6
4       Nanotech Simulation: Review 2024                    24.6
...                                  ...                     ...
4995       AI Challenge: Experience 2023                    22.0
4996         VR Challenge: Analysis 2023                    26.3
4997       AI Challenge: Experience 2023                    25.2
4998         VR Synthesis: Showcase 2023                    24.5
4999        AI Simulation: Showcase 2025                    25.2

      Total Subscribers  Members Count  AI Generated Content (%)  \
0               8264152         303319                         9
1               8768222         384629                        62
2               6163386         361743                        31
3               4712268          58483                         5
4               9592017         333873                        63
...                 ...            ...                       ...
4995            2665835         267828                        19
4996             136992          20019                        67
4997            2314561         407346                        99
4998            6954832         308313                         1
4999            6785166          23263                        52

      Neural Interface Compatible Metaverse Integration Level  \
0                            True                        Full
1                           False                         NaN
2                            True                    Advanced
3                           False                         NaN
4                            True                         NaN
...                           ...                         ...
4995                         True                        Full
4996                         True                        Full
4997                         True                    Advanced
4998                         True                       Basic
4999                         True                        Full

      Quantum Computing Topics Holographic Content Rating  Engagement Score  \
0                            5                         3D         130655.44
1                            4                         3D         138624.73
2                            6                         1D          97442.53
3                           15                         1D          74500.50
4                           12                         3D         151648.85
...                        ...                        ...               ...
4995                         1                         3D          42146.59
4996                        14                         4D           2165.83
4997                         5                         1D          36592.98
4998                         9                         4D         109955.22
4999                         8                         3D         107272.81

      Content Value Index
0                     6.2
1                    21.4
2                    13.5
3                    12.0
4                    27.3
...                   ...
4995                  6.4
4996                 29.9
4997                 33.2
4998                  6.6
4999                 21.2

[5000 rows x 14 columns]


<class 'pandas.DataFrame'>

In [17]:
# With Squeese, type is Series
df_one = pd.read_csv("../Datasets/youtube_2025_dataset_one_column.csv").squeeze("columns")
print(df_one)
print("\n")
print(type(df_one))

0                   Smith-Ross Labs
1                  Sandoval PLC Hub
2       Jones, Moore and Ho Network
3              Mitchell-Hooper Labs
4                Wilson LLC Studios
                   ...
4995          Flores-Daniel Studios
4996       Spencer and Sons Studios
4997         Obrien-Roberts Studios
4998                   King Ltd Hub
4999              Henry Ltd Studios
Name: Channel Name, Length: 5000, dtype: str


<class 'pandas.Series'>

### Two Columns

In [18]:
pd.read_csv("../Datasets/youtube_2025_dataset_two_columns.csv")

           Youtuber Name  Total Videos
0             Eric Patel            68
1     Cynthia Harrington           128
2          Amanda Walker           282
3      Jessica Nelson MD           302
4        Matthew Sherman           129
...                  ...           ...
4995       Jasmine Smith           106
4996      John Rasmussen           130
4997          Lisa Burke           179
4998          Steve Diaz           182
4999         Austin Tate            92

[5000 rows x 2 columns]

## `index_col` : specific column you want to refer it to as your index column

In [19]:
df_two = pd.read_csv('../Datasets/youtube_2025_dataset_two_columns.csv', index_col='Youtuber Name').squeeze('columns')
print(df_two)

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int64

# `Attribute in Series`

## 1. `.values` : representing only the values of the given series

In [20]:
df_one.values # values = youtube name

<ArrowStringArray>
[                    'Smith-Ross Labs',                    'Sandoval PLC Hub',
         'Jones, Moore and Ho Network',                'Mitchell-Hooper Labs',
                  'Wilson LLC Studios',                   'Myers Ltd Network',
                   'Huber Inc Network',              'Baxter-Collins Studios',
                   'Morrow-Abbott Hub',               'Jackson Group Network',
 ...
                     'Cole-Sharp Labs', 'Sherman, Mcgee and Phillips Studios',
                      'Baker-Hill Hub',    'Francis, Davis and Jones Network',
     'Whitaker, Horn and Escobar Labs',               'Flores-Daniel Studios',
            'Spencer and Sons Studios',              'Obrien-Roberts Studios',
                        'King Ltd Hub',                   'Henry Ltd Studios']
Length: 5000, dtype: str

In [21]:
df_two.values # value = total videos of youtube

array([ 68, 128, 282, ..., 179, 182,  92], dtype=int64)

## 2. `.index`: return only the index values from the given column

In [22]:
df.index

RangeIndex(start=0, stop=5000, step=1)

In [23]:
df_one.index

RangeIndex(start=0, stop=5000, step=1)

In [24]:
df_two.index

Index(['Eric Patel', 'Cynthia Harrington', 'Amanda Walker',
       'Jessica Nelson MD', 'Matthew Sherman', 'Anna Berry', 'Richard Arnold',
       'Stephanie Potter', 'Teresa Aguirre', 'Anne Adkins',
       ...
       'Erin Bradley', 'Brooke Perez', 'Nicholas Jordan', 'Howard Phelps',
       'Sharon Graham', 'Jasmine Smith', 'John Rasmussen', 'Lisa Burke',
       'Steve Diaz', 'Austin Tate'],
      dtype='str', name='Youtuber Name', length=5000)

## 3. `dtype`: provides the idea about the data type of the values that you are storing

In [25]:
df.dtype

AttributeError: 'DataFrame' object has no attribute 'dtype'

In [26]:
df_one.dtype

In [27]:
df_two.dtype

dtype('int64')

## 4. `.astype`: change the data size

In [28]:
print(df_two)
print(df_two.dtype)
new_astype = df_two.astype('int32')
print("\n")
print(new_astype)
print(new_astype.dtype)

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int64
int64


Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int32
int32

## 5. `size`: provide the idea about the total numbers of rows in dataset

In [29]:
print(df)
print('\n')
print(df.size)

                     Channel Name       Youtuber Name  Total Videos  \
0                 Smith-Ross Labs          Eric Patel            68
1                Sandoval PLC Hub  Cynthia Harrington           128
2     Jones, Moore and Ho Network       Amanda Walker           282
3            Mitchell-Hooper Labs   Jessica Nelson MD           302
4              Wilson LLC Studios     Matthew Sherman           129
...                           ...                 ...           ...
4995        Flores-Daniel Studios       Jasmine Smith           106
4996     Spencer and Sons Studios      John Rasmussen           130
4997       Obrien-Roberts Studios          Lisa Burke           179
4998                 King Ltd Hub          Steve Diaz           182
4999            Henry Ltd Studios         Austin Tate            92

                              Best Video  Avg Video Length (min)  \
0              VR Challenge: Review 2023                    24.8
1     Nanotech Simulation: Analysis 2024                    22.9
2     Metaverse Interface: Analysis 2024                    24.0
3               VR Protocol: Review 2023                    24.6
4       Nanotech Simulation: Review 2024                    24.6
...                                  ...                     ...
4995       AI Challenge: Experience 2023                    22.0
4996         VR Challenge: Analysis 2023                    26.3
4997       AI Challenge: Experience 2023                    25.2
4998         VR Synthesis: Showcase 2023                    24.5
4999        AI Simulation: Showcase 2025                    25.2

      Total Subscribers  Members Count  AI Generated Content (%)  \
0               8264152         303319                         9
1               8768222         384629                        62
2               6163386         361743                        31
3               4712268          58483                         5
4               9592017         333873                        63
...                 ...            ...                       ...
4995            2665835         267828                        19
4996             136992          20019                        67
4997            2314561         407346                        99
4998            6954832         308313                         1
4999            6785166          23263                        52

      Neural Interface Compatible Metaverse Integration Level  \
0                            True                        Full
1                           False                         NaN
2                            True                    Advanced
3                           False                         NaN
4                            True                         NaN
...                           ...                         ...
4995                         True                        Full
4996                         True                        Full
4997                         True                    Advanced
4998                         True                       Basic
4999                         True                        Full

      Quantum Computing Topics Holographic Content Rating  Engagement Score  \
0                            5                         3D         130655.44
1                            4                         3D         138624.73
2                            6                         1D          97442.53
3                           15                         1D          74500.50
4                           12                         3D         151648.85
...                        ...                        ...               ...
4995                         1                         3D          42146.59
4996                        14                         4D           2165.83
4997                         5                         1D          36592.98
4998                         9                         4D         109955.22
4999                         8                         3D         107272.81

      Content Value Index
0                     6.2
1                    21.4
2                    13.5
3                    12.0
4                    27.3
...                   ...
4995                  6.4
4996                 29.9
4997                 33.2
4998                  6.6
4999                 21.2

[5000 rows x 14 columns]


70000

## 6. `shape`: provide the idea about the rows and column in the dataset

In [30]:
print(df.shape)
print(df_one.shape)
print(df_two.shape)

(5000, 14)
(5000,)
(5000,)

## 7. `ndim`: provide the idea about the dimension of the given dataset

In [31]:
df.ndim

2

## 8. `name`: provides the idea about the name of the series

## 9. `is_unique`: provides us the idea about whether the uniques values are their or not inside the column

In [32]:
df_two

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int64

In [33]:
df_two.name

'Total Videos'

In [34]:
df_two.is_unique # False: not unique value

False

In [35]:
pd.Series([11,2,3,4]).is_unique

True

---
# `Series Methods`
---

## 1. `head()`
- provides the Top Preview of Data as the Top 5 Rows of the Dataframe or Series
- Quite helpful with providing the preview of the dataset and if want to  preview Top 10 rows then pass 10 as an argument to head(10) function

In [36]:
df.head()

,Channel Name,Youtuber Name,Total Videos,Best Video,Avg Video Length (min),Total Subscribers,Members Count,AI Generated Content (%),Neural Interface Compatible,Metaverse Integration Level,Quantum Computing Topics,Holographic Content Rating,Engagement Score,Content Value Index
0,Smith-Ross Labs,Eric Patel,68,VR Challenge: Review 2023,24.8,8264152,303319,9,True,Full,5,3D,130655.44,6.2
1,Sandoval PLC Hub,Cynthia Harrington,128,Nanotech Simulation: Analysis 2024,22.9,8768222,384629,62,False,NaN,4,3D,138624.73,21.4
2,"Jones, Moore and Ho Network",Amanda Walker,282,Metaverse Interface: Analysis 2024,24.0,6163386,361743,31,True,Advanced,6,1D,97442.53,13.5
3,Mitchell-Hooper Labs,Jessica Nelson MD,302,VR Protocol: Review 2023,24.6,4712268,58483,5,False,NaN,15,1D,74500.50,12.0
4,Wilson LLC Studios,Matthew Sherman,129,Nanotech Simulation: Review 2024,24.6,9592017,333873,63,True,NaN,12,3D,151648.85,27.3

In [37]:
df_two.head()

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
Name: Total Videos, dtype: int64

In [38]:
df_two.head(1)

Youtuber Name
Eric Patel    68
Name: Total Videos, dtype: int64

## 2. `tail()`
- provides the Botom Preview of Data as the Bottom 5 Rows of the Dataframe or Series
- Quite helpful with providing the preview of the dataset and if want to  preview Bottom 10 rows then pass 10 as an argument to head(10) function

In [39]:
df_two

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int64

In [40]:
df_two.tail()

Youtuber Name
Jasmine Smith     106
John Rasmussen    130
Lisa Burke        179
Steve Diaz        182
Austin Tate        92
Name: Total Videos, dtype: int64

## 3. `sample()`:
- provide any custom or random row from the dataset for us to preview it

In [41]:
df_two.sample()

Youtuber Name
Laurie Singh    349
Name: Total Videos, dtype: int64

In [42]:
df_two.sample(5) # any 5 random rows from data set

Youtuber Name
Bobby Martin        113
Andrew Howard       470
Julie Thompson       67
Adrian Rodriguez    137
Stanley Kennedy     487
Name: Total Videos, dtype: int64

## 4. `value_count()`
- provide the idea about the count of the values ( categorical values )
- if i am having a column where the categorical value count I want then use value_count()
- eg. any name repeated, show how many time repeated

In [45]:
youtube = pd.read_csv('../Datasets/youtube_2025_dataset_202504061614.csv')
print(youtube)

                     Channel Name       Youtuber Name  Total Videos  \
0                 Smith-Ross Labs          Eric Patel            68
1                Sandoval PLC Hub  Cynthia Harrington           128
2     Jones, Moore and Ho Network       Amanda Walker           282
3            Mitchell-Hooper Labs   Jessica Nelson MD           302
4              Wilson LLC Studios     Matthew Sherman           129
...                           ...                 ...           ...
4995        Flores-Daniel Studios       Jasmine Smith           106
4996     Spencer and Sons Studios      John Rasmussen           130
4997       Obrien-Roberts Studios          Lisa Burke           179
4998                 King Ltd Hub          Steve Diaz           182
4999            Henry Ltd Studios         Austin Tate            92

                              Best Video  Avg Video Length (min)  \
0              VR Challenge: Review 2023                    24.8
1     Nanotech Simulation: Analysis 2024                    22.9
2     Metaverse Interface: Analysis 2024                    24.0
3               VR Protocol: Review 2023                    24.6
4       Nanotech Simulation: Review 2024                    24.6
...                                  ...                     ...
4995       AI Challenge: Experience 2023                    22.0
4996         VR Challenge: Analysis 2023                    26.3
4997       AI Challenge: Experience 2023                    25.2
4998         VR Synthesis: Showcase 2023                    24.5
4999        AI Simulation: Showcase 2025                    25.2

      Total Subscribers  Members Count  AI Generated Content (%)  \
0               8264152         303319                         9
1               8768222         384629                        62
2               6163386         361743                        31
3               4712268          58483                         5
4               9592017         333873                        63
...                 ...            ...                       ...
4995            2665835         267828                        19
4996             136992          20019                        67
4997            2314561         407346                        99
4998            6954832         308313                         1
4999            6785166          23263                        52

      Neural Interface Compatible Metaverse Integration Level  \
0                            True                        Full
1                           False                         NaN
2                            True                    Advanced
3                           False                         NaN
4                            True                         NaN
...                           ...                         ...
4995                         True                        Full
4996                         True                        Full
4997                         True                    Advanced
4998                         True                       Basic
4999                         True                        Full

      Quantum Computing Topics Holographic Content Rating  Engagement Score  \
0                            5                         3D         130655.44
1                            4                         3D         138624.73
2                            6                         1D          97442.53
3                           15                         1D          74500.50
4                           12                         3D         151648.85
...                        ...                        ...               ...
4995                         1                         3D          42146.59
4996                        14                         4D           2165.83
4997                         5                         1D          36592.98
4998                         9                         4D         109955.22
4999                         8                         3D         107272.81

      Content Value Index
0                     6.2
1                    21.4
2                    13.5
3                    12.0
4                    27.3
...                   ...
4995                  6.4
4996                 29.9
4997                 33.2
4998                  6.6
4999                 21.2

[5000 rows x 14 columns]

In [46]:
yt_name = youtube['Youtuber Name']
print(yt_name)
print('\n')
print(yt_name.value_counts())

0               Eric Patel
1       Cynthia Harrington
2            Amanda Walker
3        Jessica Nelson MD
4          Matthew Sherman
               ...
4995         Jasmine Smith
4996        John Rasmussen
4997            Lisa Burke
4998            Steve Diaz
4999           Austin Tate
Name: Youtuber Name, Length: 5000, dtype: str


Youtuber Name
Jennifer Smith    4
Michael Smith     4
James Miller      4
Stephen Taylor    3
David Williams    3
                 ..
Sharon Graham     1
John Rasmussen    1
Lisa Burke        1
Steve Diaz        1
Austin Tate       1
Name: count, Length: 4831, dtype: int64

In [47]:
avg = youtube['Avg Video Length (min)']
print(avg)
print(type(avg))
print("\n")
avg.value_counts() # show how many times repeated a value in dataset

0       24.8
1       22.9
2       24.0
3       24.6
4       24.6
        ...
4995    22.0
4996    26.3
4997    25.2
4998    24.5
4999    25.2
Name: Avg Video Length (min), Length: 5000, dtype: float64
<class 'pandas.Series'>

Avg Video Length (min)
24.1    276
23.8    264
23.9    256
24.2    253
24.0    251
       ...
19.9      1
27.3      1
28.0      1
21.0      1
20.7      1
Name: count, Length: 78, dtype: int64

## 5. `sort_values()`: 
- sort the values in ascending manner
- useful for the numerical column
- sort the value in descending manner , passing ascending = False in the sort_values(ascending=False)

In [48]:
avg.sort_values() # youtube video length in ascending manner

500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [49]:
avg.sort_values(ascending=False)

361     28.9
1467    28.4
364     28.3
925     28.1
2748    28.0
        ...
3704    20.7
171     20.6
1713    19.9
451     19.3
500     19.1
Name: Avg Video Length (min), Length: 5000, dtype: float64

### `Method Channing` :
- use multiple methods together to get the required value in a way the first method's output  will be input for the next one and so on..

In [50]:
avg.sort_values(ascending=False).head(1)

361    28.9
Name: Avg Video Length (min), dtype: float64

In [51]:
avg.sort_values(ascending=False).head(1).values[0]

28.9

## 5. `inplace` : in order to change the data permanent

In [52]:
avg.sort_values(ascending=False)

361     28.9
1467    28.4
364     28.3
925     28.1
2748    28.0
        ...
3704    20.7
171     20.6
1713    19.9
451     19.3
500     19.1
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [53]:
avg_copy = avg.copy()

In [54]:
avg_copy.sort_values(inplace=True) # now it is permanent change

In [55]:
avg_copy

500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

## 6. `sort_index`: sorts the index in descending manner

In [56]:
df_two

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int64

In [57]:
df_two.sort_index()

Youtuber Name
Aaron Archer        136
Aaron Bishop        151
Aaron Brown          51
Aaron Burns         314
Aaron Carrillo      210
                   ...
Zachary Phillips    478
Zachary Russell      81
Zachary Shelton     446
Zoe Peterson         78
Zoe Smith            83
Name: Total Videos, Length: 5000, dtype: int64