---
# `Important Parameters in read_csv()`
---

This notebook explains important pandas `read_csv()` parameters using separate markdown and code cells.

## Setup

Import pandas before using `pd.read_csv()`.

In [1]:
import pandas as pd

## Basic Syntax

**Definition:** `pd.read_csv()` reads a CSV file and returns a pandas DataFrame.

**Syntax:**

```python
pd.read_csv("data.csv")
```

In [2]:
df = pd.read_csv("../datasets/titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

## 1. `sep`

**Definition:** Specifies the delimiter used in the file. The default delimiter is comma `,`.

- Comma-separated file
`df = pd.read_csv("data.csv", sep=",")`

- Semicolon-separated file
`df = pd.read_csv("data.csv", sep=";")`

- Tab-separated file
`pd.read_csv("../datasets/katalog_gempa_v2.tsv", sep="\t")`

In [3]:
# Tab-separated file
df = pd.read_csv("../datasets/katalog_gempa_v2.tsv", sep="\t")

C:\Users\arunk\AppData\Local\Temp\ipykernel_23856\2074531752.py:2: DtypeWarning: Columns (0: magTypeFM) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../datasets/katalog_gempa_v2.tsv", sep="\t")

In [4]:
df.head()

,eventID,datetime,latitude,longitude,magnitude,mag_type,depth,phasecount,azimuth_gap,location,...,doubleCouple,clvd,strikeNP1,dipNP1,rakeNP1,strikeNP2,dipNP2,rakeNP2,azgapFM,misfit
0,bmg2008vkye,2008-11-01 00:31:25.143741+00:00,-0.604440,98.895531,2.989742,MLv,20,6,146.70738,"Southern Sumatra, Indonesia",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,bmg2008vlag,2008-11-01 01:34:29.660856+00:00,-6.611860,129.387220,5.507549,mb,30,62,45.46764,Banda Sea,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,bmg2008vlaj,2008-11-01 01:38:14.802129+00:00,-3.650586,127.990680,3.539674,MLv,5,4,331.97404,"Seram, Indonesia",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,bmg2008vlbt,2008-11-01 02:20:05.909515+00:00,-4.198925,128.097000,2.424314,MLv,5,5,326.37993,Banda Sea,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,bmg2008vlcd,2008-11-01 02:32:18.756155+00:00,-4.091891,128.200470,2.410045,MLv,10,5,314.65474,Banda Sea,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 2. `header`

**Definition:** Specifies which row contains column names.

In [5]:
# First row as header
df = pd.read_csv("../datasets/titanic.csv", header=1)
df.head()

,892,0,3,"Kelly, Mr. James",male,34.5,0.1,0.2,330911,7.8292,Unnamed: 10,Q
0,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
1,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
2,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
3,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
4,897,0,3,"Svensson, Mr. Johan Cervin",male,14.0,0,0,7538,9.2250,NaN,S

In [6]:
# No header in file
df = pd.read_csv("../datasets/titanic.csv", header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11
0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
2,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47,1,0,363272,7,NaN,S
3,894,0,2,"Myles, Mr. Thomas Francis",male,62,0,0,240276,9.6875,NaN,Q
4,895,0,3,"Wirz, Mr. Albert",male,27,0,0,315154,8.6625,NaN,S

## 3. `names`

**Definition:** Assigns custom column names while reading the file.

In [7]:
df = pd.read_csv("../datasets/student_depression_dataset.csv")
df.columns

Index(['id', 'Gender', 'Age', 'City', 'Profession', 'Academic Pressure',
       'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction',
       'Sleep Duration', 'Dietary Habits', 'Degree',
       'Have you ever had suicidal thoughts ?', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness', 'Depression'],
      dtype='str')

In [8]:
df = pd.read_csv(
    "../datasets/student_depression_dataset.csv",
    header=None,
    names=['Student ID', 'Sex', 'Age', 'City', 'Profession', 'Academic Pressure',
       'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction',
       'Sleep Duration', 'Dietary Habits', 'Degree',
       'Have you ever had suicidal thoughts ?', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness', 'Depression']
)
df.head()

,Student ID,Sex,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
1,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1
2,8,Female,24.0,Bangalore,Student,2.0,0.0,5.9,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0
3,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0
4,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1

## 4. `usecols`

**Definition:** Reads only selected columns from the CSV file.

In [9]:
# Select columns by name
df = pd.read_csv(
    "../datasets/student_depression_dataset.csv",
    usecols=["Age", "Gender"]
)
df.head()

   Gender   Age
0    Male  33.0
1  Female  24.0
2    Male  31.0
3  Female  28.0
4  Female  25.0

In [10]:
# Select columns by index position
df = pd.read_csv(
    "../datasets/student_depression_dataset.csv",
    usecols=[0, 5]
)
df.head()

   id  Academic Pressure
0   2                5.0
1   8                2.0
2  26                3.0
3  30                3.0
4  32                4.0

## 5. `index_col`

**Definition:** Specifies a column to use as the DataFrame index.

In [11]:
df = pd.read_csv(
    "../datasets/titanic.csv",
    index_col="PassengerId"
)
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

## 7. `squeeze`: convert into series

In [12]:
pd.read_csv("../datasets/titanic.csv", usecols=['Survived']).squeeze()

0      0
1      1
2      0
3      0
4      1
      ..
413    0
414    1
415    0
416    0
417    0
Name: Survived, Length: 418, dtype: int64

## 6. `dtype`

**Definition:** Specifies the data type of one or more columns.

In [13]:
pd.read_csv(
    "../datasets/student_depression_dataset.csv",
    dtype={
        "Age": 'int32',
        "id": 'int32',
    }
).info()

<class 'pandas.DataFrame'>
RangeIndex: 27901 entries, 0 to 27900
Data columns (total 18 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     27901 non-null  int32
 1   Gender                                 27901 non-null  str
 2   Age                                    27901 non-null  int32
 3   City                                   27901 non-null  str
 4   Profession                             27901 non-null  str
 5   Academic Pressure                      27901 non-null  float64
 6   Work Pressure                          27901 non-null  float64
 7   CGPA                                   27901 non-null  float64
 8   Study Satisfaction                     27901 non-null  float64
 9   Job Satisfaction                       27901 non-null  float64
 10  Sleep Duration                         27901 non-null  str
 11  Dietary Habits                         27901 non-null  str
 12  Degree                                 27901 non-null  str
 13  Have you ever had suicidal thoughts ?  27901 non-null  str
 14  Work/Study Hours                       27901 non-null  float64
 15  Financial Stress                       27901 non-null  str
 16  Family History of Mental Illness       27901 non-null  str
 17  Depression                             27901 non-null  int64
dtypes: float64(6), int32(2), int64(1), str(9)
memory usage: 5.1 MB

## 7. `nrows`

**Definition:** Reads only the first `N` rows from the CSV file.

In [14]:
pd.read_csv(
    "../datasets/student_depression_dataset.csv",
    nrows=100
)

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,525,Female,34.0,Hyderabad,Student,3.0,0.0,5.32,3.0,0.0,'7-8 hours',Unhealthy,B.Tech,Yes,7.0,4.0,Yes,1
96,529,Male,22.0,Nagpur,Student,4.0,0.0,6.27,4.0,0.0,'5-6 hours',Moderate,B.Com,Yes,10.0,3.0,No,1
97,530,Male,23.0,Lucknow,Student,3.0,0.0,7.70,2.0,0.0,'More than 8 hours',Unhealthy,M.Com,No,11.0,3.0,Yes,0
98,534,Male,24.0,Kalyan,Student,3.0,0.0,9.66,1.0,0.0,'Less than 5 hours',Healthy,M.Pharm,Yes,9.0,1.0,Yes,1
99,535,Male,21.0,Delhi,Student,5.0,0.0,8.10,1.0,0.0,'More than 8 hours',Moderate,B.Arch,Yes,9.0,3.0,No,1

## 8. `skiprows`

**Definition:** Skips selected rows while reading the CSV file.

In [15]:
pd.read_csv(
    "../datasets/Chocolate Sales.csv",
)

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,04/01/2022,"$5,320.00",180
1,Van Tuxwell,India,85% Dark Bars,01/08/2022,"$7,896.00",94
2,Gigi Bohling,India,Peanut Butter Cubes,07/07/2022,"$4,501.00",91
3,Jan Morforth,Australia,Peanut Butter Cubes,27/04/2022,"$12,726.00",342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24/02/2022,"$13,685.00",184
...,...,...,...,...,...,...
3277,Karlen McCaffrey,Australia,Spicy Special Slims,17/05/2024,"$5,303.58",354
3278,Jehu Rudeforth,USA,White Choc,07/06/2024,"$7,339.32",121
3279,Ches Bonnell,Canada,Organic Choco Syrup,26/07/2024,$616.09,238
3280,Dotty Strutley,India,Eclairs,28/07/2024,"$2,504.62",397
3281,Karlen McCaffrey,India,70% Dark Bites,23/05/2024,"$5,915.87",355

In [16]:
# Skip first 2 rows
pd.read_csv(
    "../datasets/Chocolate Sales.csv",
    skiprows=2
)

,Van Tuxwell,India,85% Dark Bars,01/08/2022,"$7,896.00",94
0,Gigi Bohling,India,Peanut Butter Cubes,07/07/2022,"$4,501.00",91
1,Jan Morforth,Australia,Peanut Butter Cubes,27/04/2022,"$12,726.00",342
2,Jehu Rudeforth,UK,Peanut Butter Cubes,24/02/2022,"$13,685.00",184
3,Van Tuxwell,India,Smooth Sliky Salty,06/06/2022,"$5,376.00",38
4,Oby Sorrel,UK,99% Dark & Pure,25/01/2022,"$13,685.00",176
...,...,...,...,...,...,...
3275,Karlen McCaffrey,Australia,Spicy Special Slims,17/05/2024,"$5,303.58",354
3276,Jehu Rudeforth,USA,White Choc,07/06/2024,"$7,339.32",121
3277,Ches Bonnell,Canada,Organic Choco Syrup,26/07/2024,$616.09,238
3278,Dotty Strutley,India,Eclairs,28/07/2024,"$2,504.62",397
3279,Karlen McCaffrey,India,70% Dark Bites,23/05/2024,"$5,915.87",355

In [17]:
# Skip specific rows
pd.read_csv(
    "../datasets/Chocolate Sales.csv",
    skiprows=[1, 3, 5]
)

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Van Tuxwell,India,85% Dark Bars,01/08/2022,"$7,896.00",94
1,Jan Morforth,Australia,Peanut Butter Cubes,27/04/2022,"$12,726.00",342
2,Van Tuxwell,India,Smooth Sliky Salty,06/06/2022,"$5,376.00",38
3,Oby Sorrel,UK,99% Dark & Pure,25/01/2022,"$13,685.00",176
4,Gunar Cockshoot,Australia,After Nines,24/03/2022,"$3,080.00",73
...,...,...,...,...,...,...
3274,Karlen McCaffrey,Australia,Spicy Special Slims,17/05/2024,"$5,303.58",354
3275,Jehu Rudeforth,USA,White Choc,07/06/2024,"$7,339.32",121
3276,Ches Bonnell,Canada,Organic Choco Syrup,26/07/2024,$616.09,238
3277,Dotty Strutley,India,Eclairs,28/07/2024,"$2,504.62",397
3278,Karlen McCaffrey,India,70% Dark Bites,23/05/2024,"$5,915.87",355

## 9. `skipfooter`

**Definition:** Skips rows from the bottom of the file. Use `engine="python"` with this parameter.

In [18]:
pd.read_csv(
    "../datasets/Chocolate Sales.csv",
    skipfooter=2,
    engine="python"
)

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,04/01/2022,"$5,320.00",180
1,Van Tuxwell,India,85% Dark Bars,01/08/2022,"$7,896.00",94
2,Gigi Bohling,India,Peanut Butter Cubes,07/07/2022,"$4,501.00",91
3,Jan Morforth,Australia,Peanut Butter Cubes,27/04/2022,"$12,726.00",342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24/02/2022,"$13,685.00",184
...,...,...,...,...,...,...
3275,Beverie Moffet,India,Almond Choco,24/05/2024,"$3,634.26",100
3276,Brien Boise,Australia,Peanut Butter Cubes,19/08/2024,$352.51,196
3277,Karlen McCaffrey,Australia,Spicy Special Slims,17/05/2024,"$5,303.58",354
3278,Jehu Rudeforth,USA,White Choc,07/06/2024,"$7,339.32",121
3279,Ches Bonnell,Canada,Organic Choco Syrup,26/07/2024,$616.09,238

## 10. `na_values`

**Definition:** Treats specified values as missing values, or `NaN`.

In [19]:
pd.read_csv(
    "../datasets/titanic.csv",
    na_values=['NaN', "No", '']
)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [20]:
pd.read_csv(
    "../datasets/titanic.csv",
    na_values=["NaN", "Null", "?"]
)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

## 11. `keep_default_na`

**Definition:** Controls whether pandas should use its default list of missing-value markers.

In [21]:
pd.read_csv(
    "../datasets/titanic.csv",
    keep_default_na=False
)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47,1,0,363272,7,,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62,0,0,240276,9.6875,,Q
3,895,0,3,"Wirz, Mr. Albert",male,27,0,0,315154,8.6625,,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22,1,1,3101298,12.2875,,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,,0,0,A.5. 3236,8.05,,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39,0,0,PC 17758,108.9,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.25,,S
416,1308,0,3,"Ware, Mr. Frederick",male,,0,0,359309,8.05,,S
417,1309,0,3,"Peter, Master. Michael J",male,,1,1,2668,22.3583,,C

## 12. `parse_dates`

**Definition:** Converts selected columns into datetime format while reading the file.

In [22]:
pd.read_csv(
    "../datasets/katalog_gempa_v2.tsv",
    parse_dates=["datetime"],
    sep='\t'
)

C:\Users\arunk\AppData\Local\Temp\ipykernel_23856\1669280304.py:1: DtypeWarning: Columns (0: magTypeFM) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv(

,eventID,datetime,latitude,longitude,magnitude,mag_type,depth,phasecount,azimuth_gap,location,...,doubleCouple,clvd,strikeNP1,dipNP1,rakeNP1,strikeNP2,dipNP2,rakeNP2,azgapFM,misfit
0,bmg2008vkye,2008-11-01 00:31:25.143741+00:00,-0.604440,98.895531,2.989742,MLv,20,6,146.707380,"Southern Sumatra, Indonesia",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,bmg2008vlag,2008-11-01 01:34:29.660856+00:00,-6.611860,129.387220,5.507549,mb,30,62,45.467640,Banda Sea,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,bmg2008vlaj,2008-11-01 01:38:14.802129+00:00,-3.650586,127.990680,3.539674,MLv,5,4,331.974040,"Seram, Indonesia",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,bmg2008vlbt,2008-11-01 02:20:05.909515+00:00,-4.198925,128.097000,2.424314,MLv,5,5,326.379930,Banda Sea,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,bmg2008vlcd,2008-11-01 02:32:18.756155+00:00,-4.091891,128.200470,2.410045,MLv,10,5,314.654740,Banda Sea,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141124,bmg2026lgfr,2026-06-09 22:35:00.605139+00:00,-3.525839,122.263176,2.860996,M,10,13,109.713367,"Sulawesi, Indonesia",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141125,bmg2026lgfz,2026-06-09 22:44:06.096179+00:00,5.278846,125.562416,3.795191,M,10,12,152.763316,"Mindanao, Philippines",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141126,bmg2026lggz,2026-06-09 23:14:42.872263+00:00,5.162628,125.468277,4.932787,Mw,49,15,336.573707,"Mindanao, Philippines",...,0.490959,0.509041,319.869627,73.50817,-138.572289,215.805519,50.620541,-21.546807,336.573707,0.117474
141127,bmg2026lgia,2026-06-09 23:45:38.129962+00:00,4.917941,125.603600,3.904007,M,10,6,231.794224,"Talaud Islands, Indonesia",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141128,bmg2026lgih,2026-06-09 23:53:52.523784+00:00,-0.988137,120.276550,2.456952,M,12,10,109.640816,"Minahassa Peninsula, Sulawesi",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
pd.read_csv(
    "../datasets/Chocolate Sales.csv",
    parse_dates=['Date']
).info()

<class 'pandas.DataFrame'>
RangeIndex: 3282 entries, 0 to 3281
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   3282 non-null   str
 1   Country        3282 non-null   str
 2   Product        3282 non-null   str
 3   Date           3282 non-null   str
 4   Amount         3282 non-null   str
 5   Boxes Shipped  3282 non-null   int64
dtypes: int64(1), str(5)
memory usage: 324.8 KB

## 13. `dayfirst`

**Definition:** Handles date formats where the day comes before the month, such as `25-12-2026`.

In [24]:
df = pd.read_csv(
    "data.csv",
    parse_dates=["Date"],
    dayfirst=True
)

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

## 14. `encoding`

**Definition:** Specifies the file encoding used to read text correctly.

In [25]:
pd.read_csv(
    "../datasets/titanic.csv",
    encoding="utf-8"
)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [26]:
pd.read_csv(
    "../datasets/katalog_gempa_v2.tsv",
    encoding="latin1"
)

                                                   eventID\tdatetime\tlatitude\tlongitude\tmagnitude\tmag_type\tdepth\tphasecount\tazimuth_gap\tlocation\tagency\tdatetimeFM\tlatFM\tlonFM\tmagFM\tmagTypeFM\tdepthFM\tphasecountFM\tAzGapFM\tscalarMoment\tMrr\tMtt\tMpp\tMrt\tMrp\tMtp\tvarianceReduction\tdoubleCouple\tclvd\tstrikeNP1\tdipNP1\trakeNP1\tstrikeNP2\tdipNP2\trakeNP2\tazgapFM\tmisfit
bmg2008vkye\t2008-11-01 00:31:25.143741+00:00\t...   Indonesia\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t...
bmg2008vlag\t2008-11-01 01:34:29.660856+00:00\t...                                                NaN
bmg2008vlaj\t2008-11-01 01:38:14.802129+00:00\t...   Indonesia\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t...
bmg2008vlbt\t2008-11-01 02:20:05.909515+00:00\t...                                                NaN
bmg2008vlcd\t2008-11-01 02:32:18.756155+00:00\t...                                                NaN
...                                                                                               ...
bmg2026lgfr\t2026-06-09 22:35:00.605139+00:00\t...   Indonesia\tBMKG\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t...
bmg2026lgfz\t2026-06-09 22:44:06.096179+00:00\t...   Philippines\tBMKG\t\t\t\t\t\t\t\t\t\t\t\t\t\t...
bmg2026lggz\t2026-06-09 23:14:42.872263+00:00\t...   Philippines\tBMKG\t2026-06-09T23:14:42.872263...
bmg2026lgia\t2026-06-09 23:45:38.129962+00:00\t...   Indonesia\tBMKG\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t...
bmg2026lgih\t2026-06-09 23:53:52.523784+00:00\t...   Sulawesi\tBMKG\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\...

[141129 rows x 1 columns]

## 15. `thousands`

**Definition:** Handles thousands separators in numeric columns.

In [ ]:
pd.read_csv(
    "../datasets/titanic.csv",
    thousands=","
)

## 17. `Convertors`

In [ ]:
def station(value):
    if value == 'Q':
        return 'Queenstown'
    
    return value

In [ ]:
pd.read_csv("../datasets/titanic.csv", converters={'Embarked': station})

## 16. `decimal`

**Definition:** Specifies the decimal separator used in numeric values.

In [ ]:
pd.read_csv(
    "../datasets/Chocolate Sales.csv",
    decimal=","
)

## 17. `true_values` / `false_values`

**Definition:** Converts selected text values into Boolean `True` and `False`.

In [ ]:
pd.read_csv(
    "../datasets/titanic.csv",
    true_values=["Yes"],
    false_values=["No"]
)

## 18. `chunksize`

**Definition:** Reads large files in smaller chunks instead of loading the full file at once.

In [ ]:
df = pd.read_csv(
    "../datasets/International_Education_Costs.csv",
    chunksize=100
)

for d in df:
    print(d.shape)

## 19. `compression`

**Definition:** Reads compressed files such as ZIP or GZIP files.

In [ ]:
df = pd.read_csv(
    "data.csv.zip",
    compression="zip"
)

In [ ]:
df = pd.read_csv(
    "data.csv.gz",
    compression="gzip"
)

## 20. `engine`

**Definition:** Specifies the parser engine. Common values are `"c"` and `"python"`.

In [ ]:
pd.read_csv(
    "../datasets/Chocolate Sales.csv",
    engine="c"
)

In [ ]:
pd.read_csv(
    "../datasets/Chocolate Sales.csv",
    engine="python"
)

## 21. `low_memory`

**Definition:** Controls memory optimization while reading large datasets. Use `low_memory=False` for more consistent type detection.

In [ ]:
df = pd.read_csv(
    "data.csv",
    low_memory=False
)

## 22. `on_bad_lines`

**Definition:** Handles malformed rows in the CSV file.

In [ ]:
pd.read_csv(
    "../datasets/titanic.csv",
    on_bad_lines="skip"
)

## 23. `quotechar`

**Definition:** Specifies the character used for quoted strings.

In [ ]:
df = pd.read_csv(
    "data.csv",
    quotechar='"'
)

## 24. `comment`

**Definition:** Ignores lines that start with the specified comment character.

In [ ]:
df = pd.read_csv(
    "data.csv",
    comment="#"
)

## Most Important Parameters for Interviews

1. `sep`
2. `header`
3. `names`
4. `usecols`
5. `index_col`
6. `dtype`
7. `nrows`
8. `skiprows`
9. `parse_dates`
10. `na_values`
11. `encoding`
12. `chunksize`

In [ ]:
df = pd.read_csv(
    "data.csv",
    sep=",",
    usecols=["Name", "Salary"],
    parse_dates=["Joining_Date"],
    na_values=["NA", "?"],
    encoding="utf-8"
)

df.head()