---
# `Automated Data Cleaning`
---

## Types of Missing Data:
1. Missing Completely At Random ( MCAR )
2. Missing At Random ( MAR )
3. Missing Not At Random ( MNAR )

---

In [142]:
import pandas as pd

In [143]:
df = pd.read_csv("../datasets/unclean_smartwatch_health_data.csv")

In [144]:
df.head()

,User ID,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
0,4174.0,58.939776,98.809650,5450.390578,7.167235622316564,Highly Active,1
1,NaN,NaN,98.532195,727.601610,6.538239375570314,Highly_Active,5
2,1860.0,247.803052,97.052954,2826.521994,ERROR,Highly Active,5
3,2294.0,40.000000,96.894213,13797.338044,7.367789630207228,Actve,3
4,2130.0,61.950165,98.583797,15679.067648,NaN,Highly_Active,6

In [145]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   User ID                 9799 non-null   float64
 1   Heart Rate (BPM)        9600 non-null   float64
 2   Blood Oxygen Level (%)  9700 non-null   float64
 3   Step Count              9900 non-null   float64
 4   Sleep Duration (hours)  9850 non-null   str
 5   Activity Level          9800 non-null   str
 6   Stress Level            9800 non-null   str
dtypes: float64(4), str(3)
memory usage: 811.5 KB

In [146]:
df['User ID'].isnull().sum()

np.int64(201)

### User ID not required, we have to remove it

In [147]:
df = df.drop(columns=['User ID'])

In [148]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        9600 non-null   float64
 1   Blood Oxygen Level (%)  9700 non-null   float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 733.3 KB

## `Heart Rate (BPM)`

In [149]:
df['Heart Rate (BPM)'].isnull().sum()

np.int64(400)

In [150]:
df[df['Heart Rate (BPM)'].isnull() == True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
1,NaN,98.532195,727.601610,6.538239375570314,Highly_Active,5
17,NaN,96.052853,3488.919508,6.718661172525927,Seddentary,4
75,NaN,100.000000,3124.118038,4.229887888280923,Actve,1
105,NaN,98.276558,3039.112276,5.209658021888749,NaN,6
158,NaN,99.478461,11559.663606,6.470651489160172,Highly_Active,7
...,...,...,...,...,...,...
9875,NaN,99.842527,4454.770218,5.520745925308887,Sedentary,3
9956,NaN,100.000000,3584.236177,6.659533807452561,Highly_Active,5
9971,NaN,99.319841,26.215769,6.367659085134144,Active,10
9990,NaN,100.000000,3817.269018,8.595259517189332,Seddentary,2
9998,NaN,98.401058,3364.788855,5.691233932149209,Active,8

Note: Completely Missing At Randon, there is no relation between any columns

### `drop missing data: dropna()`
- First Way to clean missing data
- Note:  If missing data is less than 5 % of total data, we can completely remove it

### `Mean / Median Imputation`
- Second Way to clean is fill the missing data with the Mean or Median of all Rows of that Column
- While Going with Mean Value: Check for the Outliers

Mean: Aveage of all values
Median : middle of whole data from low to high 
Mode: Most Frequent Value

In [151]:
df['Heart Rate (BPM)'].describe()

count    9600.000000
mean       76.035462
std        19.412483
min        40.000000
25%        64.890152
50%        75.220601
75%        85.198249
max       296.593970
Name: Heart Rate (BPM), dtype: float64

In [152]:
df[df['Heart Rate (BPM)'] > 295.593970]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
4185,296.59397,95.415588,54698.646371,8.4611474189254,NaN,10

In [153]:
df['Heart Rate (BPM)'].mean()

np.float64(76.03546175646017)

In [154]:
df['Heart Rate (BPM)'].median()

np.float64(75.22060125775644)

In [155]:
df['Heart Rate (BPM)'].mode()

0    40.0
Name: Heart Rate (BPM), dtype: float64

In [156]:
df['Heart Rate (BPM)'] = df['Heart Rate (BPM)'].fillna(df['Heart Rate (BPM)'].median())

In [157]:
df['Heart Rate (BPM)'].isnull().sum()

np.int64(0)

In [158]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  9700 non-null   float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 733.3 KB

## `Blood Oxygen Level ( % )`

In [159]:
df['Blood Oxygen Level (%)'].isnull().sum()

np.int64(300)

In [160]:
df[df['Blood Oxygen Level (%)'].isnull() == True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
10,101.914938,NaN,2987.568640,7.541956463173237,Sedentary,9
21,68.310104,NaN,1058.374274,6.456918401449286,Actve,3
133,77.907578,NaN,15672.467752,9.079469571860296,Sedentary,10
134,78.227923,NaN,789.365922,3.5252990125882064,Seddentary,3
187,89.486636,NaN,2689.849911,5.737108446097524,Seddentary,6
...,...,...,...,...,...,...
9834,64.803112,NaN,1647.308449,8.04238137746177,Highly Active,7
9861,57.617790,NaN,14269.737149,6.390686112594759,Highly_Active,9
9885,75.281591,NaN,3852.160740,8.970316986352344,Actve,NaN
9905,87.693723,NaN,2364.028205,3.5490963940132865,Seddentary,3
9979,58.797407,NaN,359.210435,8.035879532058063,Active,5

In [161]:
df.describe()

       Heart Rate (BPM)  Blood Oxygen Level (%)    Step Count
count      10000.000000             9700.000000   9900.000000
mean          76.002867               97.841581   6985.685885
std           19.020902                1.732863   6885.809680
min           40.000000               90.791208      0.910138
25%           65.322796               96.662683   2021.039657
50%           75.220601               98.010642   4962.534599
75%           84.791711               99.376179   9724.902880
max          296.593970              100.000000  62486.690753

In [162]:
df['Blood Oxygen Level (%)'] = df['Blood Oxygen Level (%)'].fillna(df['Blood Oxygen Level (%)'].mean())

In [163]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 733.3 KB

---
### `Forward Fill and Backward Fill in Missing Value Imputation`
- After identifying missing values in a dataset, one way to handle them is by using the values from nearby rows instead of statistical measures like mean or median.

- Two commonly used techniques are:

    - Forward Fill (FFill)
    - Backward Fill (BFill)

- These methods are especially useful for **time-series data** and datasets where neighboring values are related.

---

### ` **Forward Fill (FFill)** `: replaces a missing value with the **last valid (non-missing) value** that appears before it.
#### Original Data

| Day | Temperature |
|-----|-------------|
| Monday | 30 |
| Tuesday | NaN |
| Wednesday | NaN |
| Thursday | 32 |
| Friday | 31 |

#### After Forward Fill

| Day | Temperature |
|-----|-------------|
| Monday | 30 |
| Tuesday | 30 |
| Wednesday | 30 |
| Thursday | 32 |
| Friday | 31 |

The missing values are filled using the previous available value.

---

### `**Backward Fill**` (BFill): replaces a missing value with the **next valid (non-missing) value**.

## How It Works

### Original Data

| Day | Temperature |
|-----|-------------|
| Monday | 30 |
| Tuesday | NaN |
| Wednesday | NaN |
| Thursday | 32 |
| Friday | 31 |

### After Backward Fill

| Day | Temperature |
|-----|-------------|
| Monday | 30 |
| Tuesday | 32 |
| Wednesday | 32 |
| Thursday | 32 |
| Friday | 31 |

The missing values are filled using the next available value.

---

### `Forward Fill vs Backward Fill`

| Feature | Forward Fill (FFill) | Backward Fill (BFill) |
|----------|----------------------|-----------------------|
| Uses | Previous value | Next value |
| Direction | Top → Bottom | Bottom → Top |
| Best For | Time-series, sensor data | Missing values at the beginning or when future values are reliable |
| Pandas Function | `ffill()` | `bfill()` |

---

### When Should You Use Forward Fill?

Use Forward Fill when:

- Data is sequential or time-based.
- The previous value is expected to remain valid until a new value appears.

### Examples

- Stock prices
- Temperature readings
- Sensor measurements
- Inventory levels

---

### When Should You Use Backward Fill?

Use Backward Fill when:

- The next value can reasonably represent the missing value.
- Missing values occur before the first recorded observation.

### Examples

- Scheduled events
- Future-known data
- Survey responses where later values apply

---

### Advantages

#### Forward Fill

- Simple and fast.
- Preserves trends in time-series data.
- Easy to implement.

#### Backward Fill

- Useful when future observations are more appropriate.
- Effective for leading missing values.

---

### Limitations

### Forward Fill

- Can propagate outdated values.
- Not suitable if values change rapidly.

### Backward Fill

- Uses future information, which may not be available in real-time applications.
- May introduce data leakage in predictive models if applied incorrectly.

---

## `Step Count`

In [164]:
df['Step Count'].isnull().sum()

np.int64(100)

In [165]:
df[df['Step Count'].isnull() == True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
136,70.593014,97.473981,NaN,3.439287691081752,Highly_Active,6
204,75.220601,98.710637,NaN,5.756958709255954,Highly_Active,8
603,69.084103,99.627473,NaN,6.358184719715759,Highly_Active,7
716,83.258294,98.704757,NaN,5.486240700986009,Seddentary,3
739,97.506420,97.651407,NaN,7.465981460156365,Active,6
...,...,...,...,...,...,...
9097,62.072133,96.810967,NaN,5.828570383973958,Seddentary,6
9121,54.793814,99.670176,NaN,6.686430627866978,Seddentary,2
9191,101.777396,100.000000,NaN,8.07989468005159,Active,10
9527,75.220601,94.694312,NaN,4.186856483292383,Seddentary,4
9565,90.411615,95.009355,NaN,8.582820460042822,Sedentary,4

In [166]:
# Forward Filling
df['Step Count'] = df['Step Count'].ffill()

In [167]:
df['Step Count'].isnull().sum()

np.int64(0)

In [168]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 733.3 KB

---

## `Sleep Duration`

In [169]:
df['Sleep Duration (hours)'].dtype

In [170]:
df.head()

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
0,58.939776,98.809650,5450.390578,7.167235622316564,Highly Active,1
1,75.220601,98.532195,727.601610,6.538239375570314,Highly_Active,5
2,247.803052,97.052954,2826.521994,ERROR,Highly Active,5
3,40.000000,96.894213,13797.338044,7.367789630207228,Actve,3
4,61.950165,98.583797,15679.067648,NaN,Highly_Active,6

In [171]:
df[df['Sleep Duration (hours)'] == 'ERROR']

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
2,247.803052,97.052954,2826.521994,ERROR,Highly Active,5
62,115.078288,99.928041,1918.372142,ERROR,Highly_Active,4
71,64.799778,94.743857,4613.859266,ERROR,Highly_Active,10
81,41.709895,96.857347,1413.015778,ERROR,Highly_Active,4
92,70.243810,97.171134,2336.583406,ERROR,Highly Active,7
...,...,...,...,...,...,...
9901,63.369107,96.229029,6656.786482,ERROR,Active,4
9912,75.933666,97.386073,1813.072248,ERROR,Sedentary,10
9927,87.579045,98.768633,3727.161872,ERROR,Active,1
9943,91.834863,96.145378,38831.465057,ERROR,Active,4
9951,70.335328,98.560133,1997.442874,ERROR,Highly_Active,9

In [172]:
# converting Error value or missing value 
# Object --> Numeric --> Pandas --> to_numeric()

In [173]:
df['Sleep Duration (hours)'] = pd.to_numeric(df['Sleep Duration (hours)'], errors = 'coerce')

In [174]:
df[df['Sleep Duration (hours)'] == 'ERROR']

Empty DataFrame
Columns: [Heart Rate (BPM), Blood Oxygen Level (%), Step Count, Sleep Duration (hours), Activity Level, Stress Level]
Index: []

In [175]:
df['Sleep Duration (hours)'].dtype

dtype('float64')

In [176]:
# oultier: irrelevant

In [177]:
df['Sleep Duration (hours)'].mean()

np.float64(6.505462918406444)

In [178]:
df['Sleep Duration (hours)'].median()

np.float64(6.503308362112644)

In [179]:
df['Sleep Duration (hours)'] = df['Sleep Duration (hours)'].fillna(df['Sleep Duration (hours)'].mean())

In [180]:
df['Sleep Duration (hours)'].isnull().sum()

np.int64(0)

In [181]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  10000 non-null  float64
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(4), str(2)
memory usage: 571.3 KB

## `Activity Level`

# Fill Up Categorical Columns
- Fill with Mode Value --> Most Frequently repeating value in columns

In [182]:
df['Activity Level'].isnull().sum()

np.int64(200)

In [183]:
df['Activity Level'].mode()

0    Seddentary
Name: Activity Level, dtype: str

In [184]:
df['Activity Level'] = df['Activity Level'].fillna('Seddentary')

In [185]:
df['Activity Level'].isnull().sum()

np.int64(0)

In [186]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  10000 non-null  float64
 4   Activity Level          10000 non-null  str
 5   Stress Level            9800 non-null   str
dtypes: float64(4), str(2)
memory usage: 572.1 KB

---

## `Stress Level`

### Constant Imputation : When you want to fill missing value with constant value like 'unknown', 999

In [187]:
df['Stress Level'].isnull().sum()

np.int64(200)

In [188]:
df['Stress Level'].value_counts()

Stress Level
2            1007
7            1006
6            1001
3             995
1             984
9             976
4             966
10            954
5             945
8             917
Very High      49
Name: count, dtype: int64

In [189]:
df['Stress Level'] = df['Stress Level'].fillna(5)

In [190]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  10000 non-null  float64
 4   Activity Level          10000 non-null  str
 5   Stress Level            10000 non-null  object
dtypes: float64(4), object(1), str(1)
memory usage: 560.0+ KB

---

# `Different Techniques of Imputation in Machine Learning`

## `What is Imputation?`

### Definition

**Imputation** is the process of replacing missing values in a dataset with estimated or meaningful values instead of removing the data.

> **Goal:** Preserve as much information as possible while improving data quality.

---

# Why is Imputation Important?

Missing values can:

- Reduce model accuracy
- Cause errors during model training
- Introduce bias
- Reduce the amount of usable data

Imputation helps create a complete dataset for Machine Learning models.

---

# `Types of Imputation Techniques`

There are two broad categories:

## 1. `Simple Imputation`

Uses simple statistical measures or nearby values.

### Techniques

- Mean Imputation
- Median Imputation
- Mode (Most Frequent) Imputation
- Constant Value Imputation
- Forward Fill (FFill)
- Backward Fill (BFill)

---

## 2. `Advanced Imputation`

Uses Machine Learning or statistical algorithms to estimate missing values.

### Techniques

- KNN Imputer
- Iterative Imputer (MICE)
- Regression Imputation
- Random Forest Imputation
- Multiple Imputation
- Deep Learning-based Imputation

---

# 1.` Mean Imputation`

## Definition

Replace missing numerical values with the **average (mean)** of the column.

### Formula

\[
\text{Mean} = \frac{\text{Sum of Values}}{\text{Number of Values}}
\]

### Example

| Age |
|------|
| 20 |
| 25 |
| NaN |
| 35 |

Mean = (20 + 25 + 35) / 3 = **26.67**

After Imputation:

| Age |
|------|
| 20 |
| 25 |
| 26.67 |
| 35 |

### Best For

- Numerical data
- Normally distributed data

### Limitation

Sensitive to outliers.

---

# 2. `Median Imputation`

## Definition

Replace missing values with the **middle value** after sorting the data.

### Example

Values:

20, 25, 30, 1000

Median = **27.5**

### Best For

- Numerical data with outliers
- Skewed distributions

### Advantage

Less affected by extreme values than the mean.

---

# 3. `Mode (Most Frequent) Imputation`

## Definition

Replace missing values with the most frequently occurring value.

### Example

| Gender |
|---------|
| Male |
| Female |
| Male |
| NaN |

Mode = **Male**

After Imputation:

| Gender |
|---------|
| Male |
| Female |
| Male |
| Male |

### Best For

Categorical variables.

---

# 4. `Constant Value Imputation`

## Definition

Replace missing values with a fixed value.

### Examples

- 0
- Unknown
- Not Available
- Missing

### Example

| City |
|------|
| Delhi |
| NaN |
| Mumbai |

After:

| City |
|------|
| Delhi |
| Unknown |
| Mumbai |

---

# 5. `Forward Fill (FFill)`

## Definition

Replace missing values with the **previous valid value**.

### Example

| Value |
|--------|
| 10 |
| NaN |
| NaN |
| 15 |

After:

| Value |
|--------|
| 10 |
| 10 |
| 10 |
| 15 |

### Best For

- Time-series data
- Sensor readings

---

# 6. `Backward Fill (BFill)`

## Definition

Replace missing values with the **next valid value**.

### Example

| Value |
|--------|
| 10 |
| NaN |
| NaN |
| 15 |

After:

| Value |
|--------|
| 10 |
| 15 |
| 15 |
| 15 |

---

# 7. `KNN Imputer`

## Definition

KNN (K-Nearest Neighbors) Imputer fills missing values by looking at similar data points.

### How It Works

1. Find the K nearest neighbors.
2. Calculate the average (or weighted average).
3. Replace the missing value.

### Example

If similar customers have ages:

24, 25, 26

Missing age = **25**

### Best For

- Medium-sized datasets
- Correlated features

---

# 8. `Iterative Imputer (MICE)`

## Definition

Iterative Imputer predicts missing values using other features in the dataset.

Each feature is modeled as a function of the remaining features.

### Example

Missing Salary can be predicted using:

- Age
- Education
- Experience

### Advantage

More accurate than simple imputation.

---

# 9. `Regression Imputation`

## Definition

Uses a regression model to predict missing values.

### Example

Predict house price using:

- Area
- Bedrooms
- Location

Missing house price is estimated using the regression model.

---

# 10. `Random Forest Imputation`

## Definition

Uses a Random Forest model to estimate missing values.

### Advantages

- Handles nonlinear relationships.
- High prediction accuracy.
- Works well with complex datasets.

---

# 11. `Multiple Imputation`

## Definition

Creates multiple versions of the dataset by filling missing values in different ways.

The results are then combined to reduce uncertainty.

### Best For

- Statistical analysis
- Medical research
- Scientific studies

---

# Comparison of Imputation Techniques

| Technique | Data Type | Handles Outliers | Complexity |
|------------|-----------|------------------|------------|
| Mean | Numerical | ❌ No | Easy |
| Median | Numerical | ✅ Yes | Easy |
| Mode | Categorical | N/A | Easy |
| Constant | Any | N/A | Easy |
| Forward Fill | Sequential | N/A | Easy |
| Backward Fill | Sequential | N/A | Easy |
| KNN | Numerical | ✅ Moderate | Medium |
| Iterative | Mixed | ✅ Yes | High |
| Regression | Numerical | Moderate | High |
| Random Forest | Mixed | ✅ Yes | High |
| Multiple Imputation | Mixed | ✅ Yes | Very High |

---

# Choosing the Right Technique

| Situation | Recommended Technique |
|------------|----------------------|
| Normal numerical data | Mean |
| Numerical data with outliers | Median |
| Categorical data | Mode |
| Time-series data | Forward Fill |
| Leading missing values | Backward Fill |
| Correlated features | KNN Imputer |
| High accuracy required | Iterative Imputer |
| Complex relationships | Random Forest Imputer |

---

# 2. `Interview Questions & Answers`

## Beginner Questions

### Q1. What is imputation?

**Answer:**
Imputation is the process of replacing missing values with estimated or meaningful values to create a complete dataset.

---

### Q2. Why do we use imputation?

**Answer:**
To handle missing data, improve model performance, and avoid losing valuable information by deleting rows or columns.

---

### Q3. Which imputation technique is best for categorical data?

**Answer:**
**Mode (Most Frequent) Imputation.**

---

### Q4. When should you use median instead of mean?

**Answer:**
Use the **median** when the data contains outliers or has a skewed distribution.

---

## Intermediate Questions

### Q5. What is the difference between KNN Imputer and SimpleImputer?

**Answer:**

* **SimpleImputer** replaces missing values using statistics like mean, median, or mode.
* **KNN Imputer** uses similar records (nearest neighbors) to estimate missing values.

---

### Q6. What is Iterative Imputer?

**Answer:**
It predicts missing values using machine learning models built from the other features in the dataset, making it more accurate than simple methods.

---

### Q7. Which imputation technique is commonly used for time-series data?

**Answer:**
**Forward Fill (`ffill`)** and **Backward Fill (`bfill`)**, depending on the context.

---

## Scenario-Based Questions

### Q8. A salary dataset contains extreme outliers. Which imputation technique would you choose?

**Answer:**
**Median Imputation**, because it is robust to outliers.

---

### Q9. Your dataset contains customer gender with some missing values. Which method is appropriate?

**Answer:**
**Mode Imputation**, as gender is a categorical variable.

---

### Q10. You need high-quality imputation for a healthcare dataset with correlated features. Which technique would you use?

**Answer:**
**Iterative Imputer** or **KNN Imputer**, as they leverage relationships between features for more accurate estimates.

---

# `Automated Data Cleaning Using Scikit Learn Library`

In [191]:
df = pd.read_csv("../Datasets/unclean_smartwatch_health_data.csv")

In [192]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   User ID                 9799 non-null   float64
 1   Heart Rate (BPM)        9600 non-null   float64
 2   Blood Oxygen Level (%)  9700 non-null   float64
 3   Step Count              9900 non-null   float64
 4   Sleep Duration (hours)  9850 non-null   str
 5   Activity Level          9800 non-null   str
 6   Stress Level            9800 non-null   str
dtypes: float64(4), str(3)
memory usage: 811.5 KB

In [193]:
df = df.drop(columns=['User ID'])

In [194]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='median')

In [195]:
# Note: store column in 2D array
df['Heart Rate (BPM)'] = imputer.fit_transform(df[['Heart Rate (BPM)']]).ravel()

In [196]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  9700 non-null   float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 733.3 KB

In [197]:
df.describe()

       Heart Rate (BPM)  Blood Oxygen Level (%)    Step Count
count      10000.000000             9700.000000   9900.000000
mean          76.002867               97.841581   6985.685885
std           19.020902                1.732863   6885.809680
min           40.000000               90.791208      0.910138
25%           65.322796               96.662683   2021.039657
50%           75.220601               98.010642   4962.534599
75%           84.791711               99.376179   9724.902880
max          296.593970              100.000000  62486.690753

In [198]:
imputer = SimpleImputer(strategy='mean')

In [199]:
df['Blood Oxygen Level (%)'] = imputer.fit_transform(df[['Blood Oxygen Level (%)']]).ravel()

In [200]:
imputer = SimpleImputer(strategy='most_frequent')

In [201]:
df['Activity Level'] = imputer.fit_transform(df[['Activity Level']]).ravel()

In [202]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          10000 non-null  str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 734.1 KB

In [203]:
imputer = SimpleImputer(strategy='constant', fill_value=5)

In [204]:
df['Stress Level'] = imputer.fit_transform(df[['Stress Level']]).ravel()

In [205]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          10000 non-null  str
 5   Stress Level            10000 non-null  object
dtypes: float64(3), object(1), str(2)
memory usage: 722.0+ KB

In [206]:
df.describe()

       Heart Rate (BPM)  Blood Oxygen Level (%)    Step Count
count      10000.000000            10000.000000   9900.000000
mean          76.002867               97.841581   6985.685885
std           19.020902                1.706669   6885.809680
min           40.000000               90.791208      0.910138
25%           65.322796               96.703718   2021.039657
50%           75.220601               97.933416   4962.534599
75%           84.791711               99.327856   9724.902880
max          296.593970              100.000000  62486.690753

In [207]:
imputer = SimpleImputer(strategy='constant', fill_value=5)