---
# `Feature Engineering`
---

## What is Feature Engineering?

**Feature Engineering** is the process of creating, selecting, modifying, and transforming features (columns) in a dataset to improve the performance of a Machine Learning model.

In simple words:

> **Feature Engineering means preparing and improving the input data so that the Machine Learning model can learn better.**

---

# Why is Feature Engineering Important?

Machine Learning models learn only from the features (input columns) we provide.

If the features are:

- Incomplete
- Incorrect
- Irrelevant
- Poorly formatted

then the model will produce poor predictions.

Good features → Better Model Performance 🚀

---

# When is Feature Engineering Performed?

Feature Engineering is performed **after EDA (Exploratory Data Analysis)** and **before training the Machine Learning model**.

### ML Pipeline

```
Business Problem
        ↓
Data Collection
        ↓
Data Cleaning
        ↓
EDA
        ↓
Feature Engineering
        ↓
Model Training
        ↓
Evaluation
```

---

# Goals of Feature Engineering

- Improve data quality
- Increase model accuracy
- Reduce noise
- Make data understandable for ML algorithms
- Create meaningful features

---

# Common Feature Engineering Techniques

## 1. Handling Missing Values

### Why?

Machine Learning algorithms cannot properly learn from missing values.

### Techniques

- Mean Imputation
- Median Imputation
- Mode Imputation
- Forward Fill
- Backward Fill
- KNN Imputer

### Example

| Age |
|------|
| 20 |
| NaN |
| 25 |

↓

| Age |
|------|
| 20 |
| 22.5 |
| 25 |

---

## 2. Handling Outliers

### Why?

Outliers can negatively affect model performance.

### Techniques

- Remove Outliers
- Cap (Winsorization)
- Log Transformation

### Example

Salary

```
25000
27000
26000
29000
5000000   ← Outlier
```

---

## 3. Encoding Categorical Variables

### Why?

Machine Learning models work with numbers, not text.

### Example

Before

| Gender |
|---------|
| Male |
| Female |

↓

After

| Gender |
|---------|
| 0 |
| 1 |

### Common Methods

- Label Encoding
- One-Hot Encoding

---

## 4. Feature Scaling

### Why?

Different numerical features may have different ranges.

Example

Age = 25

Salary = 500000

The model may give more importance to Salary because of its larger values.

Scaling brings features to a similar range.

### Common Methods

- Standardization
- Normalization

---

## 5. Feature Selection

### Why?

Not every feature is useful.

Removing irrelevant features:

- Improves accuracy
- Reduces training time
- Prevents overfitting

### Example

House Price Prediction

Useful:

- Area
- Bedrooms
- Location

Not Useful:

- House ID

---

## 6. Feature Creation

### Why?

Sometimes creating new features improves model performance.

### Example

Existing Features

- Date of Birth

New Feature

- Age

Another Example

Existing Features

- Length
- Width

New Feature

- Area = Length × Width

---

## 7. Feature Transformation

### Why?

Some algorithms work better when data follows a normal distribution.

### Techniques

- Log Transformation
- Square Root Transformation
- Box-Cox Transformation

---

# Real-Life Example

## House Price Prediction

Original Dataset

| Area | Bedrooms | House ID | Price |
|-------|-----------|----------|--------|
| 1200 | 2 | H101 | ₹40L |

### Feature Engineering

✔ Remove House ID

✔ Fill Missing Values

✔ Scale Area

✔ Encode Location

✔ Remove Outliers

↓

Clean Dataset

| Area | Bedrooms | Location | Price |
|-------|-----------|----------|--------|

Now the Machine Learning model can learn more effectively.

---

# EDA vs Feature Engineering

| EDA | Feature Engineering |
|------|----------------------|
| Understand the data | Improve the data |
| Find problems | Fix problems |
| Analyze distributions | Transform features |
| Detect outliers | Remove or handle outliers |
| Detect missing values | Fill missing values |
| Study relationships | Create better features |

---

# Interview Tips

### Remember

EDA answers:

> **"What problems exist in the data?"**

Feature Engineering answers:

> **"How can we fix or improve the data?"**

---

# Easy Memory Trick

### EDA

**Observe the Data 👀**

### Feature Engineering

**Improve the Data 🔧**

---

# Key Takeaways

- Feature Engineering improves the quality of input features.
- It is performed after EDA.
- Better features lead to better Machine Learning models.
- Common techniques include:
  - Handling missing values
  - Handling outliers
  - Encoding categorical variables
  - Feature scaling
  - Feature selection
  - Feature creation
  - Feature transformation
````

---

# 2. Interview Questions & Answers

## Beginner Questions

### Q1. What is Feature Engineering?

**Answer:**
Feature Engineering is the process of creating, selecting, and transforming features to improve the performance of a Machine Learning model.

---

### Q2. Why is Feature Engineering important?

**Answer:**
It improves data quality, helps the model learn better patterns, and increases prediction accuracy.

---

### Q3. When is Feature Engineering performed?

**Answer:**
After **EDA** and before **model training**.

---

### Q4. Name some Feature Engineering techniques.

**Answer:**

* Handling Missing Values
* Handling Outliers
* Encoding
* Feature Scaling
* Feature Selection
* Feature Creation
* Feature Transformation

---

## Intermediate Questions

### Q5. What is Feature Scaling?

**Answer:**
Feature Scaling brings numerical features to a similar range so that no single feature dominates because of its larger values.

---

### Q6. What is Feature Selection?

**Answer:**
Feature Selection is the process of choosing the most relevant features and removing irrelevant ones to improve model performance.

---

### Q7. What is the difference between Feature Selection and Feature Creation?

**Answer:**

* **Feature Selection** removes unnecessary features.
* **Feature Creation** creates new features from existing ones.

---

## Scenario-Based Questions

### Q8. Your dataset contains a "House ID" column for house price prediction. Should you keep it?

**Answer:**
No. House ID is just an identifier and usually does not help predict the house price, so it should be removed during feature selection.

---

### Q9. Your dataset has a "Date of Birth" column. What useful feature can you create?

**Answer:**
Create an **Age** feature by calculating the person's age from their date of birth.

---

# 3. 30-Second Revision

* **Feature Engineering** = Improve input features for better ML performance.
* Done **after EDA**.
* Includes:

  * Missing Value Handling
  * Outlier Handling
  * Encoding
  * Scaling
  * Feature Selection
  * Feature Creation
  * Feature Transformation

---

# 4. 2-Minute Revision

### Feature Engineering Workflow

1. Handle Missing Values.
2. Remove or treat Outliers.
3. Encode Categorical Data.
4. Scale Numerical Features.
5. Select Important Features.
6. Create New Features.
7. Transform Features if needed.

**Remember:**

* **EDA = Find Problems**
* **Feature Engineering = Solve Problems**
---

In [ ]:
import pandas as pd
import seaborn as sns

In [ ]:
test = pd.read_csv('../Datasets/titanic.csv')

In [ ]:
train = pd.read_csv('../Datasets/titanic2.csv')

In [ ]:
train.head()

In [ ]:
test.head()

In [ ]:
train.shape

In [ ]:
test.shape

In [ ]:
df = pd.concat([train, test])

In [ ]:
df.head()

In [ ]:
df.shape

In [ ]:
df.sample(5)

## `First Feature: Family Size`
- Passenger + SibSp + Parch
- Family size vs Survived : what are the chances of survival based on the family size

In [ ]:
df['Family Size'] = df['SibSp'] + df['Parch'] + 1

In [ ]:
df.head()

In [ ]:
sns.barplot(data = df, x = 'Family Size', y = 'Survived')

## `Family Type`

In [ ]:
def famType(num):
    if num >=1 and num <=3 :
        return 'Small Family'
    elif num > 3 and num <=5:
        return "Medium Family"
    else:
        return 'Large Family'

In [ ]:
df['Family Type'] = df['Family Size'].apply(famType)

In [ ]:
df.head()

In [ ]:
df['Family Type'].value_counts()

In [ ]:
df = df.reset_index(drop=True)
pd.crosstab(df['Family Type'], df['Survived'], normalize=True)*100

In [ ]:
df.head()

In [ ]:
sns.heatmap(pd.crosstab(df['Family Type'], df['Survived'], normalize=True)*100)

In [ ]:
sns.barplot(data = df, x = 'Family Type', y = 'Survived')

In [ ]:
df[df['SibSp'] == 5]

# `Individual Fare`

In [118]:
df['Individual Fare'] = (df['Fare'] / df['Family Size'])

In [119]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family Size,Family Type,Individual Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2,Small Family,3.62500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,Small Family,35.64165
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,Small Family,7.92500
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,Small Family,26.55000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1,Small Family,8.05000

In [121]:
df[df['Ticket'] == 'CA 2144'][['Family Size','Fare', 'Individual Fare']]

      Family Size  Fare  Individual Fare
59              8  46.9           5.8625
71              8  46.9           5.8625
386             8  46.9           5.8625
480             8  46.9           5.8625
678             8  46.9           5.8625
683             8  46.9           5.8625
1030            8  46.9           5.8625
1031            8  46.9           5.8625

In [122]:
df['Name']

0                                 Braund, Mr. Owen Harris
1       Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                  Heikkinen, Miss. Laina
3            Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                                Allen, Mr. William Henry
                              ...
1304                                   Spector, Mr. Woolf
1305                         Oliva y Ocana, Dona. Fermina
1306                         Saether, Mr. Simon Sivertsen
1307                                  Ware, Mr. Frederick
1308                             Peter, Master. Michael J
Name: Name, Length: 1309, dtype: str

In [126]:
df['Name Prefix'] = df['Name'].str.split(",").str[1].str.split(".").str[0].str.strip()

In [127]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family Size,Family Type,Individual Fare,Name Prefix
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2,Small Family,3.62500,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,Small Family,35.64165,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,Small Family,7.92500,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,Small Family,26.55000,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1,Small Family,8.05000,Mr

---

Based on your uploaded **Titanic datasets**, here's a production-style **Feature Engineering plan**. This is the typical workflow followed in real Machine Learning projects.

---

# Feature Engineering on Titanic Dataset

## Step 1: Understand the Features

| Column      | Type                  | Action                               |
| ----------- | --------------------- | ------------------------------------ |
| PassengerId | Identifier            | ❌ Drop                               |
| Survived    | Target Variable       | Keep                                 |
| Pclass      | Categorical (Ordinal) | Keep                                 |
| Name        | Text                  | Extract useful features              |
| Sex         | Categorical           | Encode                               |
| Age         | Numerical             | Handle Missing Values                |
| SibSp       | Numerical             | Feature Creation                     |
| Parch       | Numerical             | Feature Creation                     |
| Ticket      | Text                  | Drop or Extract Prefix               |
| Fare        | Numerical             | Handle Missing Values + Scaling      |
| Cabin       | Categorical           | Handle Missing Values / Extract Deck |
| Embarked    | Categorical           | Handle Missing Values + Encode       |

---

# Step 2: Handle Missing Values

## Age

Missing Values

* `titanic.csv` → **86**
* `titanic2.csv` → **177**

### Recommended

Since **Age** is numerical and slightly skewed,

✅ Fill using **Median**

```python
df["Age"] = df["Age"].fillna(df["Age"].median())
```

---

## Fare

Missing Values

* `titanic.csv` → **1**
* `titanic2.csv` → **0**

### Recommended

Fill with Median

```python
df["Fare"] = df["Fare"].fillna(df["Fare"].median())
```

---

## Embarked

Missing Values

* `titanic.csv` → **0**
* `titanic2.csv` → **2**

Categorical variable

Fill with Mode

```python
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])
```

---

## Cabin

Missing Values

* `titanic.csv` → **327**
* `titanic2.csv` → **687**

More than **75% missing**

### Recommended

Either

* Drop Cabin

OR

Create a new feature

```python
df["Cabin"] = df["Cabin"].fillna("Unknown")
```

or

```python
df["Deck"] = df["Cabin"].str[0]
```

---

# Step 3: Feature Creation

## Family Size

Instead of using

* SibSp
* Parch

Create

```python
df["FamilySize"] = df["SibSp"] + df["Parch"] + 1
```

Example

Father

SibSp = 1

Parch = 2

Family Size = 4

---

## Is Alone

```python
df["IsAlone"] = (df["FamilySize"] == 1).astype(int)
```

Output

| Family Size | Is Alone |
| ----------- | -------- |
| 1           | 1        |
| 4           | 0        |

---

## Extract Title

Name

```
Mr.
Mrs.
Miss.
Master.
Dr.
```

```python
df["Title"] = df["Name"].str.extract(' ([A-Za-z]+)\.')
```

Very useful feature.

---

## Extract Deck

Cabin

```
C85

↓

Deck = C
```

```python
df["Deck"] = df["Cabin"].str[0]
```

---

# Step 4: Drop Unnecessary Columns

These columns do not directly help prediction.

```python
PassengerId

Name

Ticket
```

Sometimes Cabin is also dropped.

```python
df.drop(
[
"PassengerId",
"Name",
"Ticket"
],
axis=1,
inplace=True
)
```

---

# Step 5: Encode Categorical Variables

Columns

```
Sex

Embarked

Title

Deck
```

Use

One Hot Encoding

or

Label Encoding

Example

Male

Female

↓

```
Male = 1

Female = 0
```

---

# Step 6: Feature Scaling

Scale

```
Age

Fare

FamilySize
```

Using

StandardScaler

or

MinMaxScaler

---

# Step 7: Handle Outliers

Check

```
Age

Fare
```

Using

```
Box Plot
```

If required

* Remove
* Cap
* Log Transform

---

# Final Dataset

| Feature     | Status                          |
| ----------- | ------------------------------- |
| Survived    | ✅ Target                        |
| Pclass      | ✅ Keep                          |
| Sex         | ✅ Encode                        |
| Age         | ✅ Median Imputation             |
| Fare        | ✅ Median + Scale                |
| Embarked    | ✅ Mode + Encode                 |
| FamilySize  | ✅ New Feature                   |
| IsAlone     | ✅ New Feature                   |
| Title       | ✅ New Feature                   |
| Deck        | ✅ New Feature (Optional)        |
| PassengerId | ❌ Drop                          |
| Name        | ❌ Drop (after extracting Title) |
| Ticket      | ❌ Drop                          |

---

# Complete Feature Engineering Pipeline

```
Raw Dataset
      │
      ▼
Handle Missing Values
      │
      ▼
Create New Features
(FamilySize, IsAlone, Title, Deck)
      │
      ▼
Drop Unnecessary Columns
(PassengerId, Name, Ticket)
      │
      ▼
Encode Categorical Variables
(Sex, Embarked, Title, Deck)
      │
      ▼
Feature Scaling
(Age, Fare, FamilySize)
      │
      ▼
Handle Outliers
      │
      ▼
Final Dataset
      │
      ▼
Machine Learning Model
```

## Interview Answer

**Q: What feature engineering techniques would you apply to the Titanic dataset?**

**Answer:**

1. Handle missing values (`Age` → Median, `Fare` → Median, `Embarked` → Mode).
2. Handle `Cabin` by dropping it or extracting the deck information.
3. Create new features such as `FamilySize`, `IsAlone`, `Title`, and optionally `Deck`.
4. Drop unnecessary columns like `PassengerId`, `Name` (after extracting `Title`), and `Ticket`.
5. Encode categorical variables (`Sex`, `Embarked`, `Title`, `Deck`).
6. Scale numerical features (`Age`, `Fare`, `FamilySize`) if required by the chosen algorithm.
7. Detect and handle outliers in numerical columns like `Age` and `Fare`.

This workflow reflects a typical feature engineering pipeline used for the Titanic dataset in interviews, competitions, and production ML projects.